# Generated by Django 5.1.6 on 2025-04-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_mediaattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
