# Generated by Django 5.1.6 on 2025-04-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_verification_date_profile_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
