# Generated by Django 5.1.6 on 2025-04-07 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_profile_e2e_enabled_profile_public_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='e2e_enabled',
        ),
        migrations.AddField(
            model_name='profile',
            name='private_key',
            field=models.TextField(blank=True, help_text="User's private key for E2EE (encrypted)", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_key',
            field=models.TextField(blank=True, help_text="User's public key for E2EE", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
