# Generated by Django 5.1.6 on 2025-04-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_profile_e2e_enabled_profile_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='public_key',
        ),
    ]
