# Generated by Django 5.1.6 on 2025-04-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_report_userblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspension_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspension_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
