# Generated by Django 5.1.6 on 2025-04-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_profile_is_suspended_profile_suspension_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='suspension_end',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='suspension_reason',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='suspension_start',
        ),
    ]
